### ISSUE TITLE
Give option for running scenarios multiple times

### ISSUE THREAD

**Issue by ohuu** [Root-Branch/cardamon#12]
Scenarios are run only once on a given cardamon run. The metrics we use to estimate power consumption are just proxies, they will not be perfect, also the conditions under which the computer running cardamon will change leading to variation in the results from run to run.

We can reduce the likelihood of inaccurate measurements by running scenarios multiple times and averaging on each run of cardamon.

- The number of times scenarios are run should be configurable in cardamon.toml
- The default value needs to be defined (1 or 3 or something)

**Comment by seal** [comment]
Solved in #20
