### ISSUE TITLE
Add cardamon summary to cli

### ISSUE THREAD

**Issue by ohuu** [Root-Branch/cardamon#49]
A summary is generated when cardamon runs an observation or scenario.

We need a way of generating a summary or querying the db from the cli. Something like:

 `cardamon summary <obs_scenario_name> --runs n`

**Comment by anewmandev** [comment]
Aka, "I want to see the summary of the last n runs for this scenario group" - no need to actually run the scenarios

**Comment by ohuu** [comment]
This has been implemented as the `cardamon stats` command
